### ISSUE TITLE
Apple Clang Problems

### ISSUE THREAD

**Issue by Nava2** [Morwenn/static_math#8]
I tried to build this project with XCode:

```
$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014
```

Lots of errors, and I'm unsure how to debug some of them. I'm happy to help with some guidance.

### `constant.cpp`
`test/constant.cpp:49:9: Static_assert failed ""` 
Line:
```C++
static_assert(
            std::is_same<
                decltype(1844674407370955161_c),
                smath::constant<long long, 1844674407370955161>
            >::value, "");
```

### `complex.cpp`
`test/complex.cpp:46:30: Default initialization of an object of const type 'const imaginary<int>' without a user-provided default constructor`
`test/complex.cpp:51:28: Default initialization of an object of const type 'const complex<int>' without a user-provided default constructor`
Fix:
```diff
diff --git a/test/complex.cpp b/test/complex.cpp
index 5e65dda..7f01b5f 100644
--- a/test/complex.cpp
+++ b/test/complex.cpp
@@ -43,12 +43,12 @@ constexpr auto test(complex<int> lhs, complex<long long> rhs)
 int main()
 {
     // Constructor tests
-    constexpr imaginary<int> i1;
+    constexpr imaginary<int> i1{};
     static_assert(i1.value == 0, "");
     constexpr auto i2 = imaginary<float>(5.8f);
     static_assert(smath::is_close(i2.value, 5.8f), "");
 
-    constexpr complex<int> c1;
+    constexpr complex<int> c1{};
     static_assert(c1.real == 0, "");
     static_assert(c1.imag.value == 0, "");
     constexpr auto c2 = complex<float>(1.2f, 2.5f);
```

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1515:43: Incompatible operand types ('int' and 'smath::imaginary<int>')`

It's not using the proper operand, i.e. `constexpr auto operator+(imaginary<T> lhs, imaginary<U> rhs)` it's trying to use `constexpr auto operator+(imaginary<T> lhs, Number rhs)` for some reason.

```c++
// Line 83
    static_assert(imag1 + imag1 == 2_i, "");
```

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1515:43: Incompatible operand types ('long long' and 'smath::imaginary<int>')`
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1515:43: Incompatible operand types ('int' and 'smath::imaginary<long long>')`
```c++
// Line 118:
    static_assert(8_i - comp3 == complex<int>(-5, 8), "");
```

### `ctest.cpp`
`include/static_math/detail/cmath.inl:299:12: Call to 'min' is ambiguous`

Full error, there's 7 of these with the same paths with different start points:
```
static_math/include/static_math/detail/cmath.inl:299:12: Call to 'min' is ambiguous
static_math/test/cmath.cpp:24:10: In file included from static_math/test/cmath.cpp:24:
static_math/include/static_math/cmath.h:190:14: In file included from static_math/include/static_math/cmath.h:190:
static_math/test/cmath.cpp:99:16: In instantiation of function template specialization 'smath::min<smath::constant<int, 0>, smath::constant<int, 0> >' requested here
static_math/include/static_math/detail/core.h:63:20: Candidate function [with T = smath::constant<int, 0>, U = smath::constant<int, 0>]
static_math/include/static_math/detail/core.h:70:20: Candidate function [with T = smath::constant<int, 0>, U = smath::constant<int, 0>, Rest = <>]
static_math/include/static_math/detail/core.h:79:20: Candidate function [with Integer = int, Numbers = <0, 0>]
```

The following are all "ambiguous":
```c++ 
static_assert(
        smath::min(1_c, 2_c) == 1_c, "");
    static_assert(
        smath::min(0_c, 0_c) == 0_c, "");
    static_assert(
        smath::min(-2_c, -1_c, 0_c, 1_c, 2_c) == -2_c, "");
    static_assert(
        smath::min(2_c, 1_c, 0_c, -1_c, -2_c) == -2_c, "");

    static_assert(
        smath::max(3_c, 8_c) == 8_c, "");
    static_assert(
        smath::max(-8_c, -8_c) == -8_c, "");
    static_assert(
        smath::max(8_c, -1_c, 6_c, 3_c, 5_c, 2_c, -8_c) == 8_c, "");
    static_assert(
        smath::max(-1_c, 0_c, 1_c, 2_c, 3_c, 2_c, 1_c, 0_c, -1_c) == 3_c, "");
```

### `vector.cpp`

Warnings:
```
static_math/test/vector.cpp:35:39: Suggest braces around initialization of subobject
static_math/test/vector.cpp:36:41: Suggest braces around initialization of subobject
static_math/test/vector.cpp:57:41: Suggest braces around initialization of subobject
static_math/test/vector.cpp:58:41: Suggest braces around initialization of subobject
```

### `vector.inl`

Warnings:
```
static_math/include/static_math/detail/vector.inl:34:18: Suggest braces around initialization of subobject
static_math/include/static_math/detail/vector.inl:34:18: Suggest braces around initialization of subobject
static_math/include/static_math/detail/vector.inl:41:18: Suggest braces around initialization of subobject
static_math/include/static_math/detail/vector.inl:41:18: Suggest braces around initialization of subobject
```

**Comment by Morwenn** [comment]
Uh, I don't know anything about Apple Clang specifically since I'm only using MinGW on Windows. Apparently, I should add continuous integration tests to make sure that everything goes well, but fixing those bugs might be tricky. Anyway, here are some first thoughts:

* For `constant.cpp` it might be that `long long int` is too short for the integral constant on your platform and the overflow causes an error. That's a bit strange thought.
* For `Default initialization of an object of const type 'const imaginary<int>' without a user-provided default constructor`, the error message is clear and Clang is correct: without a user-provided default constructor, you can default-initialize a `const` value. This is dumb and there is a proposed defect report against the standard to allow it, and GCC already implements the defect report. I should be able to fix that one.
* I have no idea why the overload resolution fails for the complex/imaginary types. I might have better insights once I set up the continuous integration.
* Same for `min`: I don't know why it's ambiguous.
* For the warnings, it's normal: Clang is more annoying than GCC when it comes to brace elision. To be honest, it's *too* annoying in this regard. I can fix that, but I believe that Clang should be less annoying :/

Anyway, thanks a lot for those reports. I will fix the ones about `const` default initialization and braces elision, but I fear that fixing the other ones will be harder. I will set up a continuous integration system to run the test suite when I have time, maybe in a few days. If you have more insights or manage to fix some of these things, don't hesitate to contribute :)

**Comment by Nava2** [comment]
I had already fixed most of these! I happened to step out for a coffee so I missed your response. 👎 

Check the PR I opened, I split the "fixes" into separate commits. 

> * For constant.cpp it might be that long long int is too short for the integral constant on your platform and the overflow causes an error. That's a bit strange thought.

It works with `long` on both ubuntu trusty and OSX. 

> * For Default initialization of an object of const type 'const imaginary<int>' without a user-provided default constructor, the error message is clear and Clang is correct: without a user-provided default constructor, you can default-initialize a const value. This is a bit dumb and addressed by DR 253, which is implemented by GCC (but since the DR was never officially accepted, Clang doesn't implement it). I should be able to fix that one.

I had no idea this was the case. Good to know. 

> * I have no idea why the overload resolution fails for the complex/imaginary types. I might have better insights once I set up the continuous integration.
> * Same for min: I don't know why it's ambiguous.

This was a pain in the ***. I got it, but it's not pretty. 

> * For the warnings, it's normal: Clang is more annoying than GCC when it comes to brace elision. To be honest, it's too annoying in this regard. I can fix that, but I believe that Clang should be less annoying :/

Can't disagree with you, is it due to the implicit conversions?

**Comment by Nava2** [comment]
Oh, and I have a `cmake` file that I was using to test this with.

It'd probably make CI easier. But I don't want to impose a build tool.

**Comment by Morwenn** [comment]
I'm fine with CMake and Travis; that's what I'm using on other projects. I'd gladly welcome a pull request :)

Concerning the first one, I'll probably reuse it and push it again on my side since I already fixed a few things a bit differently and I don't really like macros (yeah, that's a fine, but I write `std::enable_if_t` by hand everywhere when needed).

Concerning `min` I guess I'm not fully satisfied since other types than those satisfying `std::is_arithmetic` should be usable but discriminating against other types might be hard :/

**Comment by Morwenn** [comment]
I'm done fixing everything, except the braces warning in the test case, but it doesn't really matter: `vector` is so useless anyway that I could remove it. I managed to fix the `min`/`max` ambiguity problem while keeping a great amount of genericity instead of limiting it to built-in arithmetic types, even though I had to add a few additional tricks to do that.

I'm closing the issue: apart from the aforementioned warnings, everything compiles smoothly enough with both GCC and Apple Clang. I'm not merging your pull requests in the end, but it really helped to show what the issues were. Thanks again :)

**Comment by Nava2** [comment]
Happy to help! I wanted to use the library, but the lack of MSVC support killed it. 👎 

I have some implementations of `log()`, though -- **almost** working.

**Comment by Morwenn** [comment]
Well, I can't really help it for MSVC since the whole library relies on `constexpr` :/

You could check Bolero Murakami's Sprout instead: it reimplements huge parts of the standard library with `constexpr`, and may have better support for MSVC. Moreover, I don't really maintain this library anymore except when people open issues or merge requests; it wasn't meant to be more than a toy library.

Anyway, `log` functions would surely be a welcome addition if you can get them to work :)

**Comment by Nava2** [comment]
The `log` functions have become more of an academic exercise now. It has been much much harder than I expected. Largely due to the convergence problems of the Taylor series solutions.
